### ISSUE TITLE
Sunshine hours

### ISSUE THREAD

**Issue by Jiabing-Ruan** [dsi-principles-prog/midterm-Jiabing-Ruan#1]
The feature I would like to create is sunshine_hours. The sunshine hours = time of sun set - tine of sun rise.

What I need is how many hours. However, time_sun_rise and time_sun_set is in 'hms' format. Therefore, it requires lubridate package. **hour** and **minute** function could be used to extract hours and minutes and seperately calculate them. Finally, you just need to transfer minutes into hours and combine them together.

feature: sunshine_hours

column used: time_sun_rise, time_sun_set

key function maybe used: hour(), minute()

**Comment by baiyuchen02** [comment]
feature sunshine_hours is added as intended
